---
- name: "Verify that required string variables are defined"
  assert:
    that: 
      - "{{ ver_loop }} is defined"
      - "{{ ver_loop }} | length > 0"
      - "{{ ver_loop }} != None"
    fail_msg: "{{ ver_loop }} needs to be set for the role to work"
    success_msg: "Required variable {{ ver_loop }} is defined"
  loop_control:
    loop_var: ver_loop
  with_items:
    - server_name
    - GENERATE_SELF_SIGNED
    - AUTO_LETS_ENCRYPT
    - nextcloud_trusted


- name: open nextcloud firewall ports
  firewalld:
    port: "{{ item }}"
    zone: "public"
    permanent: true
    immediate: true
    state: enabled
  with_items:
   - "{{ pod_firewall_http_port }}"
   - "{{ pod_firewall_https_port }}"

- name: include setup_container.yml
  include_tasks: setup_container.yml